services:
  santo-backend-1:
    image: santo-rinha:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/rinha
      - DATABASE_USER=rinha
      - DATABASE_PASSWORD=rinha
      - PRIMARY_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
    depends_on:
      - santo-db
    networks:
      - santo-backend
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "85MB"

  santo-backend-2:
    image: santo-rinha:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/rinha
      - DATABASE_USER=rinha
      - DATABASE_PASSWORD=rinha
      - PRIMARY_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
    depends_on:
      - santo-db
    networks:
      - santo-backend
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "85MB"

  santo-nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - santo-backend-1
      - santo-backend-2
    networks:
      - santo-backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "15MB"

  santo-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha
    ports:
      - "5432:5432"
    networks:
      - santo-backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "165MB"

networks:
  santo-backend:
    driver: bridge
  payment-processor:
    external: true